# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycc < Formula
  desc "TUI monitor for Claude Code sessions"
  homepage "https://github.com/hwangstar156/lazycc"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.1/lazycc_0.1.1_darwin_amd64.tar.gz"
      sha256 "e739c3cc6fe4fa4b1df115fcd60653b100aff75b8d0bf2285190993d57ddc398"

      define_method(:install) do
        bin.install "lazycc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.1/lazycc_0.1.1_darwin_arm64.tar.gz"
      sha256 "51accd1c7db5d4b5a8c4d37b8474de798dcf163ecde51d8b95f9828b8afe1849"

      define_method(:install) do
        bin.install "lazycc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.1/lazycc_0.1.1_linux_amd64.tar.gz"
      sha256 "0e7f528236d26e74d50eeec8b62f35c23a2e7bc47b53264bc4256c84020ce732"
      define_method(:install) do
        bin.install "lazycc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.1/lazycc_0.1.1_linux_arm64.tar.gz"
      sha256 "dc206d1c824151aa2b9f4ed256fa4ea2c3d3168882d324f5d9a20dd67f321a30"
      define_method(:install) do
        bin.install "lazycc"
      end
    end
  end
end
