# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycc < Formula
  desc "TUI monitor for Claude Code sessions"
  homepage "https://github.com/hwangstar156/lazycc"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.2/lazycc_0.1.2_darwin_amd64.tar.gz"
      sha256 "c536db69f89981b5ebea0561120d119a70096b817d5ea5767a1b86fd4f5647bb"

      define_method(:install) do
        bin.install "lazycc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.2/lazycc_0.1.2_darwin_arm64.tar.gz"
      sha256 "3e5ed4316d02c466fc677ea7c36985e8993d5d8cc90c2cd75dd2adcfff1885fb"

      define_method(:install) do
        bin.install "lazycc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.2/lazycc_0.1.2_linux_amd64.tar.gz"
      sha256 "7da192ac1c80830419ee1797ce67316ae279329e8d6d29610437eba0f80969c4"
      define_method(:install) do
        bin.install "lazycc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.2/lazycc_0.1.2_linux_arm64.tar.gz"
      sha256 "ec451ec2e241a542d4d23878349a63a7a7d2d9936ddcba953922ad24d0ead57e"
      define_method(:install) do
        bin.install "lazycc"
      end
    end
  end
end
