# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycc < Formula
  desc "TUI monitor for Claude Code sessions"
  homepage "https://github.com/hwangstar156/lazycc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.0/lazycc_0.1.0_darwin_amd64.tar.gz"
      sha256 "f2a85e3fff5629cb92411391bd47f57259248cdca28b2d403e3d130b6544cbe2"

      define_method(:install) do
        bin.install "lazycc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.0/lazycc_0.1.0_darwin_arm64.tar.gz"
      sha256 "ca61ad7cc8629852e336963a38b101283959f8597bb7bfda3164ec4574627338"

      define_method(:install) do
        bin.install "lazycc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.0/lazycc_0.1.0_linux_amd64.tar.gz"
      sha256 "8caa17c6a5fab8822ee269450682fdc61a61df955a17752b351c76109911eac9"
      define_method(:install) do
        bin.install "lazycc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hwangstar156/lazycc/releases/download/v0.1.0/lazycc_0.1.0_linux_arm64.tar.gz"
      sha256 "2fc29fe28081a8bf568543f00efc5ad3aec635a5b49476ded9def00d01076cba"
      define_method(:install) do
        bin.install "lazycc"
      end
    end
  end
end
